package com.soumayaguenaguen.guess

import android.annotation.SuppressLint
import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.Button
import android.widget.ImageButton
import androidx.appcompat.app.AlertDialog
import kotlinx.coroutines.NonCancellable.cancel


@Suppress("DEPRECATION")
class HomeActivity : AppCompatActivity() {
    @SuppressLint("MissingInflatedId")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_home)


        val btnlevels: ImageButton = findViewById(R.id.Menu_Button)
        val btnhelp: ImageButton = findViewById(R.id.Help_Button)
        val btnplay: Button = findViewById(R.id.PlayButton)

        btnlevels.setOnClickListener {
            val intent = Intent(this, StagesActivity::class.java)
            startActivity(intent)
        }

        btnplay.setOnClickListener{
            val intentplay = Intent(this, UserinfoActivity::class.java)
            startActivity(intentplay)
        }

        btnhelp.setOnClickListener{

            val dialogBuilder = AlertDialog.Builder(this)

            // set message of alert dialog
            dialogBuilder.setMessage("This Game is about Guessing a number generated by the computer, all you have to do is Tap on the play button to start then type in random number until you guessed the right number.")
                // if the dialog is cancelable
                .setCancelable(true)
                // positive button text and action
                .setPositiveButton("Close") { dialog, id ->
                    cancel()
                }

            // create dialog box
            val alert = dialogBuilder.create()
            // set title for alert dialog box
            alert.setTitle("Do you need help?")
            // show alert dialog
            alert.show()
        }
    }
}



